name: Build
on:
  push:
jobs:
  build-project:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.2.1
      - name: Install Clingo
        run: |
          sudo add-apt-repository ppa:potassco/stable
          sudo apt update
          sudo apt-get install clingo
      - name: Build Project
        uses: threeal/cmake-action@v2.0.0
